[package]
name = "monitor-winit-example"
version = "0.0.1"
authors = ["Hiroki Moto"]
edition = "2018"
publish = false

[dependencies]
winit = "0.24"
monitor = { path = "../../", features = ["winit"] }
